site_name: Material For Mkdocs Tutorial
repo_url: https://github.com/Multi-Academy/material-for-mkdocs
repo_name: material-for-mkdocs

theme:
  name: material
  font: 
    text: Roboto
  icon:
    repo: fontawesome/brands/github
  
  palette:
    
    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/lightbulb-outline 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
        
  features:
    - navigation.footer
    - content.code.copy
    - content.code.select

plugins:
  - search
  - git-committers:
      repository: Multi-Academy/material-for-mkdocs
      branch: main